*** Variables ***
${FECHAR_MODAL}                    xpath=//android.view.View[@content-desc='Dispensar']/android.view.View/android.view.View[2]/android.view.View
${BOTAO_COMPRAR_MENU}              accessibility_id=Comprar
${BOTAO_COMPRAR}                   xpath=//android.view.View[@content-desc="COMPRAR R$ 20,00"] 
                                   #accessibility_id=COMPRAR R$ 20,00
${INSERIR_CPF}                     xpath=//android.widget.EditText
${BOTAO_CONTINUAR}                 accessibility_id=CONTINUAR
${PAGAMENTO_PIX}                   accessibility_id=PIX Rápido, prático e seguro
${BOTAO_PAGAR_PIX}                 accessibility_id=PAGAR COM PIX
${PAGAMENTO_SUCESSO}